version: '3.2'
services:
  web:
    image: "453875408421.dkr.ecr.us-east-1.amazonaws.com/cryptofeelz"
    build: .
    volumes:
      - type: volume
        source: ./gifs
        target: /usr/app/gifs
      - type: bind
        source: ./src
        target: /usr/app/src
      - type: bind
        source: ./scripts
        target: /usr/app/scripts
    ports:
     - "3000:80"
  redis:
    image: "redis:alpine"
volumes:
  gifs:
  src:
  scripts: